### ISSUE TITLE
无效的类字符串 Line#3848: obj := ComObjCreate("HTMLfile")

### ISSUE THREAD

**Issue by Sysmain** [wo52616111/capslock-plus#1]
无效的类字符串

	Line#
--->	3848: obj := ComObjCreate("HTMLfile")

**Comment by wo52616111** [comment]
有没其他线索？这个不是所有机子都会出现，我用过的三四台机子都没这个问题，没办法重现，如果有发现可以重现这个问题的方法，请说下。应该是跟 ie 有关，这句代码主要是调用 ie 引擎来实现计算的功能 （+Tab 等）

**Comment by Sysmain** [comment]
就是每次打开就会出现这个错。而且我用着时间久了，就会出现失灵的情况，然后就需要重新打开。

**Comment by wo52616111** [comment]
如果有这个错，确实应该是在初始化的时候会报这个错的。应该就是跟 ie 有关，它的作用就是生成一个调用 js(ie) 引擎的对象，如果报了这个错，那 js 引擎应该是没法用，就是 Caps+Tab 还有 Caps+F2 出来的计算板会计算不出结果。其他功能应该是没什么影响的，所以也不用太在意，点掉就好。

没有具体重现这个问题的方法，我很难查出具体是什么问题。希望有同样问题的同学可以留意下怎么重现这个问题。

至于时间久了会失灵，我在三四台电脑上用过，从没出现过这个情况，身边朋友也没反馈过这样的问题，我猜可能跟系统或者查杀软件之类的有关。

**Comment by xinn314** [comment]
[遇到过这个问题，测试了很多种情况，最后发现是因为腾讯安全管家的浏览器保护功能导致的，只要不锁定默认浏览器就不会再弹窗了。

**Comment by fqzhou** [comment]
遇到了同样的问题，确实只在初始化时候出这个问题，点掉也还能继续使用。没有安装任何管家类应用。 楼主提到的，用一段时间后快捷键失灵的情况，我也遇到了，尤其容易出现在锁屏休眠重新唤醒机器之后![image](https://user-images.githubusercontent.com/10046680/43240073-67917b6c-90c7-11e8-840f-48a65f319f1e.png)

**Comment by yixuan10000** [comment]
已经解决，在obj前global即可
![image](https://user-images.githubusercontent.com/20551341/46647034-482f0300-cbc0-11e8-80c3-30eeecf7ede7.png)
