### ISSUE TITLE
sendChar 与 doubleChar 函数重复发送字符

### ISSUE THREAD

**Issue by yrqyrqyrq99** [wo52616111/capslock-plus#101]
作者您好，我在 `lib_keysFunction.ahk` 中添加了如下函数：

```
keysFunc_doubleSmallBrackets(){
    keysFunc_doubleChar("(",")")
    return
}
```

因为我在尝试更改一些代码，因此我在 `lib_keysSet.ahk` 中尝试用原始方法映射按键功能（您使用的方法我不太会用😂）。我分别使用以下两种方式试图发送成对小括号：

**方式一**
```
CapsLock & p::
    keysFunc_doubleSmallBrackets()
    return
```

**方式二**
```
#If CapsLock
p::
    keysFunc_doubleSmallBrackets()
    return
#If
```

但是实际操作中按下 `CapsLock` 和 `P` 键后会发送 `()(()()())` 或者 `()(()()()()(()()()))` 或者其它离谱的情况，总之都不是发送单独一对小括号

我在键盘检测网站上测试了一下，按下 `CapsLock` 和 `P` 键后，键盘的响应情况如下：
![](https://s1.ax1x.com/2022/07/03/jGKLi6.png)

您可以指导我一下，出现这种情况，是哪里出问题了吗😂

**Comment by wo52616111** [comment]
https://github.com/wo52616111/capslock-plus/issues/76

这样配置可以吗？为啥要自己改代码呢？

**Comment by yrqyrqyrq99** [comment]
感谢您的回复，问题已经解决了，是我不小心把前面的一个变量删掉了😂虽然我还是不明白为啥有这个变量在就没问题

我修改代码一方面是想增加我自己习惯用的按键，另一方面也是对您代码的拆解学习

感谢您对我提问的耐心回复
