### ISSUE TITLE
Add support to transform text .

### ISSUE THREAD

**Issue by PhoenixCODE2322** [wo52616111/capslock-plus#102]
![firefox_UiTmQ6mfC0](https://user-images.githubusercontent.com/75798544/177249216-ee98ded3-7289-40e9-a8de-ad01a1e3149d.png)
this is the ahk script, will it be possible to integrate it in capslock+ https://github.com/GorvGoyl/Autohotkey-Scripts-Windows/blob/master/ctrl_caps_as_case_change.ahk

**Comment by wo52616111** [comment]
Perhpas you could rewrite it as a custom key function and use it with Capslock+'s source code like:
https://github.com/wo52616111/capslock-plus#how-to-set-a-custom-function-to-a-hotkey
