### ISSUE TITLE
在 [QSearch] 中设置了default为google，加s命令依然是百度打开搜索

### ISSUE THREAD

**Issue by willhome360** [wo52616111/capslock-plus#106]
[QSearch]
default=https://www.google.com/search?hl=zh-CN&q={q}。

3.2版本，使用2.7的布局，按如上设置，在qbar中直接搜索是google打开， 但加上s命令就无法使用默认搜索打开，比如 "s 你好"，这时是用百度搜索你好，而不是google搜索。

**Comment by wo52616111** [comment]
参考下面，把 `s` 也设置上：
https://github.com/wo52616111/capslock-plus/blob/e6390f03122ab13b2dc942c11804d1e026d1b28c/language/Simplified_Chinese.ahk#L99-L126

源码逻辑：
https://github.com/wo52616111/capslock-plus/blob/e6390f03122ab13b2dc942c11804d1e026d1b28c/lib/lib_clQ.ahk#L1636-L1648
