### ISSUE TITLE
剪贴板问题

### ISSUE THREAD

**Issue by songtengfei95** [wo52616111/capslock-plus#108]
感谢大佬软件！
我在使用capslock时，独立剪贴板会和其他软件的快捷操作冲突，只有关闭独立剪贴板功能，即在【global】下添加allowClipboard=0,其他软件才可以正常使用。但这样就无法使用Caps+C/V功能了。因此我有两个疑问，一是能否实现Caps+C/V调用系统剪贴板；二是使用独立剪贴板的目的是什么？

**Comment by wo52616111** [comment]
冲突的话确实只能选一个软件的来用了。独立剪贴板的目的就是算上系统剪贴板，你可以同时保存3份不同的剪贴板内容，随时粘贴不同的内容，方便各种比较复杂的复制粘贴操作。至于你要把 caps+c 改成系统复制 ctrl+c，你可以参考这个设置说明：https://github.com/wo52616111/capslock-plus/issues/94
