### ISSUE TITLE
有道翻译 capslock+F3 目前报错（应该今天才报错）期望作者操作一下，我好喜欢这个软件

### ISSUE THREAD

**Issue by matchyc** [wo52616111/capslock-plus#109]
报错内容：
![image](https://user-images.githubusercontent.com/57976772/179685593-0927346b-cf14-4b73-8bc5-b837e9647d51.png)

**Comment by adgad2** [comment]
现在翻译确实不能用的，有可能是有道砍了这个功能。

不知道作者会更新不...

**Comment by wo52616111** [comment]
https://github.com/wo52616111/capslock-plus/issues/46#issuecomment-681862321

**Comment by xban12** [comment]
一样的 花点心思换自己的接口吧！同样不要钱 白嫖终有一个期限的 作者辛苦了！

**Comment by matchyc** [comment]
> 一样的 花点心思换自己的接口吧！同样不要钱 白嫖终有一个期限的 作者辛苦了！

有没有什么思路？

**Comment by xban12** [comment]
可以自己去申请百度翻译的api什么的啊 每个人的账号是有免费额度的 已经够用了

从 Windows 版邮件发送

发件人: Match_yc
发送时间: 2022年7月27日 22:05
主题: Re: [wo52616111/capslock-plus] 有道翻译 capslock+F3=?UTF-8?Q?_=E7=9B=AE=E5=89=8D=E6=8A=A5=E9=94=99=EF=BC=88=E5=BA=94=E8=AF=A5=E4=BB=8A=E5=A4=A9=E6=89=8D=E6=8A=A5=E9=94=99=EF=BC=89=E6=9C=9F=E6=9C=9B=E4=BD=9C=E8=80=85=E6=93=8D=E4=BD=9C=E4=B8=80=E4=B8=8B=EF=BC=8C=E6=88=91=E5=A5=BD=E5=96=9C=E6=AC=A2=E8=BF=99=E4=B8=AA=E8=BD=AF=E4=BB=B6?==?UTF-8?Q?_=28Issue_#109=29?=

一样的 花点心思换自己的接口吧！同样不要钱 白嫖终有一个期限的 作者辛苦了！
有没有什么思路？

**Comment by matchyc** [comment]
> 

不太熟 Windows 客户端的开发，指点下代码？ 就请教下 应修改的文件 就好，不用太详细！ 感谢

**Comment by matchyc** [comment]
> 可以自己去申请百度翻译的api什么的啊 每个人的账号是有免费额度的 已经够用了 从 Windows 版邮件发送 发件人: Match_yc 发送时间: 2022年7月27日 22:05 主题: Re: [wo52616111/capslock-plus] 有道翻译 capslock+F3=?UTF-8?Q?_=E7=9B=AE=E5=89=8D=E6=8A=A5=E9=94=99=EF=BC=88=E5=BA=94=E8=AF=A5=E4=BB=8A=E5=A4=A9=E6=89=8D=E6=8A=A5=E9=94=99=EF=BC=89=E6=9C=9F=E6=9C=9B=E4=BD=9C=E8=80=85=E6=93=8D=E4=BD=9C=E4=B8=80=E4=B8=8B=EF=BC=8C=E6=88=91=E5=A5=BD=E5=96=9C=E6=AC=A2=E8=BF=99=E4=B8=AA=E8=BD=AF=E4=BB=B6?==?UTF-8?Q?_=28Issue_#109=29?= 一样的 花点心思换自己的接口吧！同样不要钱 白嫖终有一个期限的 作者辛苦了！ 有没有什么思路？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

不太熟 Windows 客户端的开发，指点下代码？ 就请教下 应修改的文件 就好，不用太详细！ 感谢

**Comment by xban12** [comment]
> > 可以自己去申请百度翻译的api什么的啊 每个人的账号是有免费额度的 已经够用了 从 Windows 版邮件发送 发件人: Match_yc 发送时间: 2022年7月27日 22:05 主题: Re: [wo52616111/capslock-plus] 有道翻译 capslock+F3=?UTF-8?Q?_=E7=9B=AE=E5=89=8D=E6=8A=A5=E9=94=99=EF=BC=88=E5=BA=94=E8=AF=A5=E4=BB=8A=E5=A4=A9=E6=89=8D=E6=8A=A5=E9=94=99=EF=BC=89=E6=9C=9F=E6=9C=9B=E4=BD=9C=E8=80=85=E6=93=8D=E4=BD=9C=E4=B8=80=E4=B8=8B=EF=BC=8C=E6=88=91=E5=A5=BD=E5=96=9C=E6=AC=A2=E8=BF=99=E4=B8=AA=E8=BD=AF=E4=BB=B6?==?UTF-8?Q?_=28Issue_#109=29?= 一样的 花点心思换自己的接口吧！同样不要钱 白嫖终有一个期限的 作者辛苦了！ 有没有什么思路？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> 不太熟 Windows 客户端的开发，指点下代码？ 就请教下 应修改的文件 就好，不用太详细！ 感谢

https://capslox.com/capslock-plus/#basicFunctions
![image](https://user-images.githubusercontent.com/77780051/181270224-579b9f24-7bfe-47e1-9451-fe3d3dd68bcb.png)
兄弟你看看这个说明 我还没试过 我就一个开发小白 之前替换过一些翻译器的api 原理应该差不多

**Comment by xban12** [comment]
> > 可以自己去申请百度翻译的api什么的啊 每个人的账号是有免费额度的 已经够用了 从 Windows 版邮件发送 发件人: Match_yc 发送时间: 2022年7月27日 22:05 主题: Re: [wo52616111/capslock-plus] 有道翻译 capslock+F3=?UTF-8?Q?_=E7=9B=AE=E5=89=8D=E6=8A=A5=E9=94=99=EF=BC=88=E5=BA=94=E8=AF=A5=E4=BB=8A=E5=A4=A9=E6=89=8D=E6=8A=A5=E9=94=99=EF=BC=89=E6=9C=9F=E6=9C=9B=E4=BD=9C=E8=80=85=E6=93=8D=E4=BD=9C=E4=B8=80=E4=B8=8B=EF=BC=8C=E6=88=91=E5=A5=BD=E5=96=9C=E6=AC=A2=E8=BF=99=E4=B8=AA=E8=BD=AF=E4=BB=B6?==?UTF-8?Q?_=28Issue_#109=29?= 一样的 花点心思换自己的接口吧！同样不要钱 白嫖终有一个期限的 作者辛苦了！ 有没有什么思路？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> 不太熟 Windows 客户端的开发，指点下代码？ 就请教下 应修改的文件 就好，不用太详细！ 感谢

兄弟你成功了吗 我好像找了很久没有找到keyForm参数应该填什么 要是你找到了麻烦给我指点一下

**Comment by xban12** [comment]
> [#46 (comment)](https://github.com/wo52616111/capslock-plus/issues/46#issuecomment-681862321)
> 
> 现在是没有合适的接口可以用。有道翻译可以说好早之前就”不能用“了，之前他们改了收费模式，免费的理论上就不能用了，不过一直还是可以用，直到现在。

作者大大麻烦问一下 我自己申请的有道api 我查了一下现在平台好像是不提供KeyFrom参数了 那我应该怎么改配置文件呢

**Comment by wo52616111** [comment]
> > [#46 (comment)](https://github.com/wo52616111/capslock-plus/issues/46#issuecomment-681862321)
> > 现在是没有合适的接口可以用。有道翻译可以说好早之前就”不能用“了，之前他们改了收费模式，免费的理论上就不能用了，不过一直还是可以用，直到现在。
> 
> 作者大大麻烦问一下 我自己申请的有道api 我查了一下现在平台好像是不提供KeyFrom参数了 那我应该怎么改配置文件呢

应该没这么简单修改一下配置就能改好，得看有道那边那参数和返回结构改成什么样，相应地修改这个文件： https://github.com/wo52616111/capslock-plus/blob/master/lib/lib_ydTrans.ahk

能发下你申请的 api 文档地址吗？

另外我试了下，我这边翻译还是可以用，试多少次都还是能用，复现不了你们的问题。。奇怪

![image](https://user-images.githubusercontent.com/12783466/181757783-7a4d15a9-5b76-493d-9a0c-8921043763af.png)

**Comment by xban12** [comment]
> > > [#46 (comment)](https://github.com/wo52616111/capslock-plus/issues/46#issuecomment-681862321)
> > > 现在是没有合适的接口可以用。有道翻译可以说好早之前就”不能用“了，之前他们改了收费模式，免费的理论上就不能用了，不过一直还是可以用，直到现在。
> > 
> > 
> > 作者大大麻烦问一下 我自己申请的有道api 我查了一下现在平台好像是不提供KeyFrom参数了 那我应该怎么改配置文件呢
> 
> 应该没这么简单修改一下配置就能改好，得看有道那边那参数和返回结构改成什么样，相应地修改这个文件： https://github.com/wo52616111/capslock-plus/blob/master/lib/lib_ydTrans.ahk
> 
> 能发下你申请的 api 文档地址吗？
> 
> 另外我试了下，我这边翻译还是可以用，试多少次都还是能用，复现不了你们的问题。。奇怪
> 
> ![image](https://user-images.githubusercontent.com/12783466/181757783-7a4d15a9-5b76-493d-9a0c-8921043763af.png)

https://ai.youdao.com/#/ 现在有道的文本翻译应该只能在这里申请吧

然后这个能用也是确实奇怪 我身边的同学就没问题 我重置了所有配置也还是不行

**Comment by matchyc** [comment]
> 成什么样，相

我测了一下，我发现当我用ipv6网络使用翻译功能时就不能用的，换成ipv4就可以了！ 有意思。。

**Comment by wo52616111** [comment]
> > > > [#46 (comment)](https://github.com/wo52616111/capslock-plus/issues/46#issuecomment-681862321)
> > > > 现在是没有合适的接口可以用。有道翻译可以说好早之前就”不能用“了，之前他们改了收费模式，免费的理论上就不能用了，不过一直还是可以用，直到现在。
> > > 
> > > 
> > > 作者大大麻烦问一下 我自己申请的有道api 我查了一下现在平台好像是不提供KeyFrom参数了 那我应该怎么改配置文件呢
> > 
> > 
> > 应该没这么简单修改一下配置就能改好，得看有道那边那参数和返回结构改成什么样，相应地修改这个文件： https://github.com/wo52616111/capslock-plus/blob/master/lib/lib_ydTrans.ahk
> > 能发下你申请的 api 文档地址吗？
> > 另外我试了下，我这边翻译还是可以用，试多少次都还是能用，复现不了你们的问题。。奇怪
> > ![image](https://user-images.githubusercontent.com/12783466/181757783-7a4d15a9-5b76-493d-9a0c-8921043763af.png)
> 
> https://ai.youdao.com/#/ 现在有道的文本翻译应该只能在这里申请吧
> 
> 然后文档应该是这个https://ai.youdao.com/DOCSIRMA/html/%E8%87%AA%E7%84%B6%E8%AF%AD%E8%A8%80%E7%BF%BB%E8%AF%91/API%E6%96%87%E6%A1%A3/%E6%96%87%E6%9C%AC%E7%BF%BB%E8%AF%91%E6%9C%8D%E5%8A%A1/%E6%96%87%E6%9C%AC%E7%BF%BB%E8%AF%91%E6%9C%8D%E5%8A%A1-API%E6%96%87%E6%A1%A3.html
> 
> 然后这个能用也是确实奇怪 我身边的同学就没问题 我重置了所有配置也还是不行

那你得直接修改源文件，把这部分的请求相关参数改成有道他们新的参数，还挺多的。。8个必要参数：

https://github.com/wo52616111/capslock-plus/blob/master/lib/lib_ydTrans.ahk#L16-L41

![image](https://user-images.githubusercontent.com/12783466/181914883-407b1e53-e086-4c79-9233-7dd7149f535b.png)

其中还要用到 sha256 加密，给你找了下 ahk 的 sha256 算法：https://github.com/jNizM/AHK_CNG#examples


然后返回结果按照他们的返回结构，修改这部分内容：

https://github.com/wo52616111/capslock-plus/blob/master/lib/lib_ydTrans.ahk#L173-L249

![image](https://user-images.githubusercontent.com/12783466/181914922-220101de-08bc-439d-97bb-1b1c653b06de.png)

--------------------

我还在考虑这个应不应该更新到 Capslock+ 源码里，如果有道收费 api 支持，那有人用的是百度翻译，是不是也要支持？有人用的谷歌翻译，是不是也要支持？没有一个好用的免费接口的话，也不知道更新上去了之后有多少人能用上。我更希望可以像之前一样，有一个限制不大的 api，大家都可以用，顺便支持上它的收费 api，要求更高的人可以自行配置一下。而不是特地去支持收费接口，更新了之后其实用的人（可能）没几个，那我感觉这样的少数需求自己改下源码就好了？

**Comment by matchyc** [comment]
> 

确实，还是免费的API用途广一点。不过ipv6没支持是我没想到的

**Comment by xban12** [comment]
> > > > > [#46 (comment)](https://github.com/wo52616111/capslock-plus/issues/46#issuecomment-681862321)
> > > > > 现在是没有合适的接口可以用。有道翻译可以说好早之前就”不能用“了，之前他们改了收费模式，免费的理论上就不能用了，不过一直还是可以用，直到现在。
> > > > 
> > > > 
> > > > 作者大大麻烦问一下 我自己申请的有道api 我查了一下现在平台好像是不提供KeyFrom参数了 那我应该怎么改配置文件呢
> > > 
> > > 
> > > 应该没这么简单修改一下配置就能改好，得看有道那边那参数和返回结构改成什么样，相应地修改这个文件： https://github.com/wo52616111/capslock-plus/blob/master/lib/lib_ydTrans.ahk
> > > 能发下你申请的 api 文档地址吗？
> > > 另外我试了下，我这边翻译还是可以用，试多少次都还是能用，复现不了你们的问题。。奇怪
> > > ![image](https://user-images.githubusercontent.com/12783466/181757783-7a4d15a9-5b76-493d-9a0c-8921043763af.png)
> > 
> > 
> > https://ai.youdao.com/#/ 现在有道的文本翻译应该只能在这里申请吧
> > 然后文档应该是这个https://ai.youdao.com/DOCSIRMA/html/%E8%87%AA%E7%84%B6%E8%AF%AD%E8%A8%80%E7%BF%BB%E8%AF%91/API%E6%96%87%E6%A1%A3/%E6%96%87%E6%9C%AC%E7%BF%BB%E8%AF%91%E6%9C%8D%E5%8A%A1/%E6%96%87%E6%9C%AC%E7%BF%BB%E8%AF%91%E6%9C%8D%E5%8A%A1-API%E6%96%87%E6%A1%A3.html
> > 然后这个能用也是确实奇怪 我身边的同学就没问题 我重置了所有配置也还是不行
> 
> 那你得直接修改源文件，把这部分的请求相关参数改成有道他们新的参数，还挺多的。。8个必要参数：
> 
> https://github.com/wo52616111/capslock-plus/blob/master/lib/lib_ydTrans.ahk#L16-L41
> 
> ![image](https://user-images.githubusercontent.com/12783466/181914883-407b1e53-e086-4c79-9233-7dd7149f535b.png)
> 
> 其中还要用到 sha256 加密，给你找了下 ahk 的 sha256 算法：https://github.com/jNizM/AHK_CNG#examples
> 
> 然后返回结果按照他们的返回结构，修改这部分内容：
> 
> https://github.com/wo52616111/capslock-plus/blob/master/lib/lib_ydTrans.ahk#L173-L249
> 
> ![image](https://user-images.githubusercontent.com/12783466/181914922-220101de-08bc-439d-97bb-1b1c653b06de.png)
> 
> 我还在考虑这个应不应该更新到 Capslock+ 源码里，如果有道收费 api 支持，那有人用的是百度翻译，是不是也要支持？有人用的谷歌翻译，是不是也要支持？没有一个好用的免费接口的话，也不知道更新上去了之后有多少人能用上。我更希望可以像之前一样，有一个限制不大的 api，大家都可以用，顺便支持上它的收费 api，要求更高的人可以自行配置一下。而不是特地去支持收费接口，更新了之后其实用的人（可能）没几个，那我感觉这样的少数需求自己改下源码就好了？

确实可以 等需求的人多了再考虑更新吧 我有空研究一下ahk 非常感谢

**Comment by wo52616111** [comment]
> > 成什么样，相
> 
> 我测了一下，我发现当我用ipv6网络使用翻译功能时就不能用的，换成ipv4就可以了！ 有意思。。 @wo52616111

能详细说下吗？怎么个操作换成 ipv4 呢？

**Comment by wo52616111** [comment]
收费版的有道 api 已经修复，（感谢 @icecreamzhao 的 PR https://github.com/wo52616111/capslock-plus/pull/114 ）。有收费接口 key 的同学可以拉最新源码试试，配置例子：

```ini
# CapsLock+settings.ini

[TTranslate]
apiType=1
appPaidID=0123456789
appPaidKey=0123456789
```

另外，在我测试来看，现在免费接口还是可以使用的

**Comment by matchyc** [comment]
> > > 成什么样，相
> > 
> > 
> > 我测了一下，我发现当我用ipv6网络使用翻译功能时就不能用的，换成ipv4就可以了！ 有意思。。 @wo52616111
> 
> 能详细说下吗？怎么个操作换成 ipv4 呢？

当我的网络ipv6访问优先时，翻译功能报错，如该issue所说。当我的网络ipv4访问优先时，翻译功能正常。这个由网络环境决定，和设置没有太大关系。由于我没有看源码，猜测是ipv6返回的报文格式和ipv4不一致等类似原因造成的bug。

**Comment by Snailser** [comment]
> 

感谢！

**Comment by BrightSoulXYHY** [comment]
> > 成什么样，相
> 
> 我测了一下，我发现当我用ipv6网络使用翻译功能时就不能用的，换成ipv4就可以了！ 有意思。。 @wo52616111

估计是免费版本的API没有加对IPV6的支持，我申请了一个收费版本的key就解决了

**Comment by zhyt0520** [comment]
> 收费版的有道 api 已经修复，（感谢 @icecreamzhao 的 PR #114 ）。有收费接口 key 的同学可以拉最新源码试试，配置例子：
> 
> ```ini
> # CapsLock+settings.ini
> 
> [TTranslate]
> apiType=1
> appPaidID=0123456789
> appPaidKey=0123456789
> ```
> 
> 另外，在我测试来看，现在免费接口还是可以使用的

2023-05-17 实测用收费版 api 可以解决问题
win10 ipv4 不修改设置，可正常使用
win11 ipv6 不修改设置会报错，添加收费接口之后不报错
