### ISSUE TITLE
Can you plese provide a function for "insert line above" similar to insert line above.

### ISSUE THREAD

**Issue by PhoenixCODE2322** [wo52616111/capslock-plus#112]
i want to add a function to insert line above but don't know . can you give a function , i will add it into user>main.ahk

**Comment by PhoenixCODE2322** [comment]
i used this but if there is a better funtion then please tell.

```
keyFunc_insertLineAbove(){
  SendInput,{Home}{Enter}{Up}
    Return
}
```

**Comment by wo52616111** [comment]
This looks good if you are trying to insert a new line at the beginning of a file. Is there something wrong with it? Why are you looking for another function?

**Comment by PhoenixCODE2322** [comment]
this actually is opposite of the function you already have " insert line below" .. just wanted to know if this is good enough as you know much more . if its good then fine.
