### ISSUE TITLE
There are many cool function idea that can be implemented in capslock_plus from Vscode.

### ISSUE THREAD

**Issue by PhoenixCODE2322** [wo52616111/capslock-plus#115]
are these possible. VSCode offer these but i wanted to have them universally in every app.
![image](https://user-images.githubusercontent.com/75798544/182012672-81e90b16-e9be-4fe1-b057-b9ae152a3573.png)
source - https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf

**Comment by PhoenixCODE2322** [comment]
updated version 
![image](https://user-images.githubusercontent.com/75798544/182022040-dee76427-0dad-4ba5-b710-4385961e47b0.png)

**Comment by wo52616111** [comment]
Sorry, but these functions are not possible to implement globally (universally), technical reason.
