### ISSUE TITLE
我看源码更新了，win版exe还没更新，哪种运行方式比较好？

### ISSUE THREAD

**Issue by willhome360** [wo52616111/capslock-plus#125]
到底是用AutoHotkey 然后运行源码比较好，还是直接运行作者的capslock+.exe比较好用？哪种方式好

**Comment by wo52616111** [comment]
跑起来都一样，看你自己吧，有条件跑源码就跑源码呗，源码确实更新一点，有能力还可以自己改代码，主要也是一些比较小的改动，所以也没有去 build 一个 exe 放出去。你可以看看这些小更新是啥，对你没影响的话其实也没差，不过跑源码倒是不怕被杀软误报，exe 经常被误报也是挺烦的。
