### ISSUE TITLE
使用划词翻译功能时经常出现如图问题，但完全找不到出现bug的规律，似乎是随机的

### ISSUE THREAD

**Issue by Sha1rholder** [wo52616111/capslock-plus#129]
![image](https://user-images.githubusercontent.com/96712109/205025631-15c80304-0e70-4577-8b51-f9ce35cd6ffc.png)

**Comment by wo52616111** [comment]
看看这个 issue: https://github.com/wo52616111/capslock-plus/issues/109

**Comment by Sha1rholder** [comment]
已解决，小白具体方法供其他人参考下：
1. 在[有道API官网](https://ai.youdao.com/console/#/service-singleton/text-translation)根据提示“创建应用”，产生应用ID和密匙（有道应该会送一些试用金的挺便宜）
![image](https://user-images.githubusercontent.com/96712109/216009786-7c44ef82-2bcd-4679-a9bc-a2508681b5bc.png)
![image](https://user-images.githubusercontent.com/96712109/216007792-ddbe7133-71ca-4106-b062-71b0462712bb.png)
复制ID和密匙
2. 在 CapsLock+settings.ini 文件下找到 [TTranslate] 后面填写以下字段
![image](https://user-images.githubusercontent.com/96712109/216008959-f68684b9-b1fe-439d-b9c1-cd5f05322bea.png)
ID填入ID内，密匙填入Key内
3. Capslock+F5 重载程序就可以使用了
