### ISSUE TITLE
在不选中任何文本的情况下使用翻译功能时音乐软件自动执行“上一首”操作

### ISSUE THREAD

**Issue by Sha1rholder** [wo52616111/capslock-plus#130]
按下Capslock+F3翻译时会出现以上状况

**Comment by Sha1rholder** [comment]
补充：有时候在已经选中文本的情况下按下Capslock+F3也会触发“下一首”操作

**Comment by wo52616111** [comment]
按下翻译功能时会发送复制快捷键来获取文本，你可以检查一下你的播放器是不是有什么全局快捷键，改一下，避免冲突应该就能好

**Comment by Sha1rholder** [comment]
> 按下翻译功能时会发送复制快捷键来获取文本，你可以检查一下你的播放器是不是有什么全局快捷键，改一下，避免冲突应该就能好

我尝试了网易云音乐修改快捷键，发现Capslock+F3似乎会同时触发Left（键盘方向键左）和Right（键盘方向键右），我在用Ctrl+Left作为“上一首”的快捷方式时Capslock+F3会触发；但我在修改网易云快捷键时直接按下Capslock+F3它会帮我设定成Ctrl+Alt+Right。
这也解释了我用Windows默认音乐播放器Mediaplayer时，按下Capslock+F3有时候会快退几秒有时候会快进几秒。理论上这个和复制快捷键应该没什么关系，可能是其他问题但我实在搞不明白
