### ISSUE TITLE
怎么 停用/恢复初始 设置

### ISSUE THREAD

**Issue by kazetyan** [wo52616111/capslock-plus#132]
有些设置是不是写到注册表之类的,关掉cl+后仍然会触发,比如绑定窗口,怎么可以在关掉cl+后就停止这些功能呢

**Comment by wo52616111** [comment]
退出 Capslock+ 不应该会有这些功能，你可以检查下是不是没有真正退出，进程还在运行？

除了一个全局启动快捷键是在退出 Capslock+ 后还能生效的：
```
启动过一次 Capslock+ 后，以后可以通过快捷键Ctrl+Alt+Capslock启动 Capslock+。
```
