### ISSUE TITLE
[疑问] 是否能将Caps做成开关（现在是一直按着+其他组合按键）

### ISSUE THREAD

**Issue by charles-lyc** [wo52616111/capslock-plus#133]
我刚接触capslock+，直觉的认为，如果是将它作为模式切换开关，按下后键盘就切成脚本专用键盘，应该会方便一些。

**Comment by wo52616111** [comment]
这样的功能是可以实现的，但是需要你下载源码修改一下，目前来说 Capslock+ 没有打算实现这样的功能额。但是改起来也是挺简单的，你只要看看这一块代码，修改一下就好：https://github.com/wo52616111/capslock-plus/blob/6fe8c4f7c103636e121687aa9557bf3f73fc2059/CapsLock%2B.ahk#L80-L112
