### ISSUE TITLE
远程桌面 ahk CapsLock 组合按键会多一个 escape在结尾

### ISSUE THREAD

**Issue by snsnsjsn** [wo52616111/capslock-plus#134]
你好，我的是本地 ahk和 远程ahk都开启。
电脑自带 远程桌面管理是唯一支持 ahk 快捷键组合映射的

但是

我 的  是把  caplock 映射为 escape

例如在本机是 capslock +j 下移，然后松开后是不会 在后面添加一个 escape的

但是在远程机器上， 我按下 CapsLock +j后，远程机器执行了  下移光标的操作后，再补上一个 escape 。导致有些操作后再补一个取消操作，结果很抓狂，本地机器却不会出现。

请我如何消除 远程机器上这个 CapsLock 映射为 escape 后，
CapsLock +其他快捷键操作完，不要再出现 escape的操作呢？

远程电脑都会带上 escape
![image](https://user-images.githubusercontent.com/11435527/211190540-386f233c-4c79-4bc5-acc0-5b25f02727cb.png)

本地电脑则不会
![image](https://user-images.githubusercontent.com/11435527/211190562-425dc824-dd31-4724-9e31-188410f2b9be.png)

本地和远程都是设置 CapsLock 为 escape 单独按下时候

`#Persistent
SetCapsLockState, Alwaysoff
$CapsLock:: 
send ,{Esc}
return
`

CapsLock+j 组合 ，包括 CTRL+shift等按键组合如下

`CapsLock & j::
if GetKeyState("Tab")=0
{
	if getkeystate("shift") = 0
	{
	    if GetKeyState("alt")=0
          ;2018年11月29日 星期四 16:03:39 send改为sendplay，同时启用右键Run with UI Access功能
          ;解决OneNote 上下键无效问题。
            ; SendPlay, {Down}
            ;2020年10月23日 星期五 18:29:32 windows 19042版本不能用 SendPlay改为 send
            Send, {Blind}{Down}
	    else
            Send, {Blind}!{Down}
	    Return
	}	
	Else
	{
	    if GetKeyState("alt")=0
          ;2018年11月29日 星期四 16:03:39 send改为sendplay，同时启用右键Run with UI Access功能
          ;解决OneNote 上下键无效问题。
            Send, {Blind}+{Down}
	    else
            Send, {Blind}+!{Down}
	    Return
	}
}
Else
{
	if getkeystate("shift") = 0
	{
	    if GetKeyState("alt")=0
          ;2018年11月29日 星期四 16:03:39 send改为sendplay，同时启用右键Run with UI Access功能
          ;解决OneNote 上下键无效问题。
            MouseMove, 0, +100, 0, R 
        Return
	}
	Else
	{
		if GetKeyState("alt")=0
			MouseMove, 0, +10, 0, R
		Return
	}
}

`

远程电脑gif动图按键演示
![2023-01-08_18-03-45](https://user-images.githubusercontent.com/11435527/211190876-3be4b3c3-9360-42b8-81d1-a261fca551d1.gif)

本地电脑 gif演示，不会多一个 escape 按键在结尾

![2023-01-08_17-58-35](https://user-images.githubusercontent.com/11435527/211190888-93643ce8-d9d4-4b8c-8d47-5b054910973f.gif)

**Comment by wo52616111** [comment]
抱歉，我没有试过这样用过，所以也不知道怎么解决。你有试过在远程的 ahk 代码里关掉 capslock->esc 的映射吗？或者远程不开 ahk，按键输入能传过去吗？

**Comment by snsnsjsn** [comment]
> 抱歉，我没有试过这样用过，所以也不知道怎么解决。你有试过在远程的 ahk 代码里关掉 capslock->esc 的映射吗？或者远程不开 ahk，按键输入能传过去吗？

非常感谢，好像可以，之前我记得测试过，这次没有出现远程后缀一个 escape的按键了。
