### ISSUE TITLE
用批处理启动时, 如何设置配置文件位置

### ISSUE THREAD

**Issue by dupontjoy** [wo52616111/capslock-plus#14]
![2](https://user-images.githubusercontent.com/4965288/32360062-6c60f1dc-c08d-11e7-8721-8a469bd50414.jpg)
如图, 我将启动Capslock+写到批处理中, 默认会自动在批处理所在文件夹生成配置文件
请问有没有办法读取Capslock+.exe所在文件夹的配置?

**Comment by lqzhgood** [comment]
13行 `cd /d ${capslockDIR}`
即可~

也就是运行 capslock 之前 先 cd 到这个目录
