### ISSUE TITLE
mac版本无法注册 登录 充值

### ISSUE THREAD

**Issue by Eagle112** [wo52616111/capslock-plus#158]

**Comment by wo52616111** [comment]
没发现有什么异常，具体是什么表现呢？

**Comment by Eagle112** [comment]
能否wx或者zfb



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月17日(周三) 晚上10:18
收件人: ***@***.***&gt;;
抄送: "Hongbin ***@***.******@***.***&gt;;
主题: Re: [wo52616111/capslock-plus] mac版本无法注册 登录 充值 (Issue #158)




 
没发现有什么异常，具体是什么表现呢？

**Comment by wo52616111** [comment]
可以的：https://capslox.com/cn/pricing/non-subscription
如果还有 capslox 的问题可以通过邮件 [support@capslox.com](mailto:support@capslox.com) 咨询
