### ISSUE TITLE
matlab 编辑器里面用caps+9 有的时候成功，有时候是出现回退一格，没有括号补全

### ISSUE THREAD

**Issue by Dotazhu** [wo52616111/capslock-plus#17]
capslock+非常好用。 但是matlab 编辑器里面用caps+9 有的时候成功，有时候是出现回退一格，没有括号补全。 请问是什么原因。
matlab里没有未选中就复制一行这个机制。

**Comment by wo52616111** [comment]
抱歉这么久才回复，因为一直也没用过 matlab，所以想着放着看有没其他人能知道解决方法，看来没有。capslock+ 主要是靠发送组合键来实现大多功能，如果在某个软件上无法用某个功能，很大可能就是组合键在那个软件上被占用之类的。
