### ISSUE TITLE
Excel大量文字复制时崩溃

### ISSUE THREAD

**Issue by dupontjoy** [wo52616111/capslock-plus#19]
Excel中复制大量文字时, Caplock+会弹窗, 然后Excel就崩溃了

**Comment by lqzhgood** [comment]
文档里面写了。

https://cjkis.me/capslock+/

原本在 Excel 中，选中一行（列）以上表格，再使用复制相关功能会导致弹出图片太大，超过部分将被截取。的问题。这是因为在 Excel 中将剪贴板大量的数据保存起来时，Excel 就会这样提醒，在其他一些剪贴板管理软件上也会有这问题，这应该算 Excel 的问题。对于这个问题目前 Capslock+ 的解决办法是，在保存剪贴板数据时取消对 Excel 窗口的激活，不让 Excel 检测到数据的保存，保存完数据再切回去，这样做的副作用是 Excel 窗口看起来会闪烁一下，暂时没有想到更好的解决办法，如果觉得接受不了建议在进行大量 Excel 下的复制操作时暂时关掉 Capslock+。

**Comment by dupontjoy** [comment]
好的, 感谢解答
