### ISSUE TITLE
如何build

### ISSUE THREAD

**Issue by zhengbli** [wo52616111/capslock-plus#2]
直接用AHK compile生产的exe不能开机用admin 权限来运行，所以没有办法覆盖全局。而且线程常常会莫名其妙死掉。但是从capslock++下载的exe并没有这些问题。所以想问是如何生成那样的exe？谢谢了。

**Comment by wo52616111** [comment]
没有啊，我就直接用 AHK 自带的那个，没什么特别操作，ahk 文件选择 cpaslock+.ahk，如果需要图标就选根目录下的 ico ，没什么特别的

**Comment by wo52616111** [comment]
补充下：
我就直接用 AutoHotkey\Compiler\Ahk2Exe.exe，刚刚生成了一个 exe，用了半个小时，似乎没发现有什么问题
![20161106225317](https://cloud.githubusercontent.com/assets/12783466/20038749/d7147b20-a473-11e6-9b0e-9046016e4959.png)

**Comment by zhengbli** [comment]
好像是可以了。可能是win 10的问题， 谢谢了！
