### ISSUE TITLE
作者大大,各位高手,如何屏蔽掉capslock的大小写功能呢

### ISSUE THREAD

**Issue by rockyx128** [wo52616111/capslock-plus#20]
这句代码 , SetCapsLockState, AlwaysOff 加在什么地方.

有时候按capslock 不小心就开启了大写功能 , 在打字速度很快的情况下 , 突然来一下 , 很影响节奏啊

**Comment by windicold** [comment]
[https://github.com/wo52616111/capslock-plus/issues/9](url)

**Comment by Blithe-Chiang** [comment]
> 这句代码 , SetCapsLockState, AlwaysOff 加在什么地方.
> 
> 有时候按capslock 不小心就开启了大写功能 , 在打字速度很快的情况下 , 突然来一下 , 很影响节奏啊

https://autohotkey.com/board/topic/123744-force-numlockalways-on-capslock-always-off-enforcer/
亲测有用

**Comment by wo52616111** [comment]
https://github.com/wo52616111/capslock-plus/issues/6
