### ISSUE TITLE
方向键的延迟，以及q键只能搜索

### ISSUE THREAD

**Issue by qiaokang0** [wo52616111/capslock-plus#21]
按住了cap和e这个往上的方向键一会再松开之后，方向键会继续持续好一会。
q键输入ch，出现chrome，然后选中后，是网页搜索ch字符，而不是打开chrome。
谢谢作者做出这么好的应用！

**Comment by qiaokang0** [comment]
方向延迟貌似是刚才暂时的问题，现在好了，q键搜索还是不好。

**Comment by windicold** [comment]
搜索ch出现chrome，需要打开chrome的话，得按Tab键补全

**Comment by wo52616111** [comment]
3.0 以后可以回车打开选中项了
