### ISSUE TITLE
能否添加对62键位键盘的优化功能？

### ISSUE THREAD

**Issue by huaiyin98** [wo52616111/capslock-plus#22]
62位键由于其较为小巧，所以天生缺少，某些键位。比如说DELETE、PG UP、PG DOWN、以及F键 。
能否添加功能对按下大写键之后的键位进行编程（更改键位功能）。
虽然适配众多62位键盘很困难，但还是希望能做出初步的功能，用户可以自行适配自己的键盘。

**Comment by wo52616111** [comment]
看看 capslock+settingsDemo.txt，可以设置按键
