### ISSUE TITLE
开机显示请求粘贴板错误

### ISSUE THREAD

**Issue by yaoya0111** [wo52616111/capslock-plus#24]
### error: Can't open clipboard for reading.
line#
4022:sClipboardAll := ClipboardAll
the current thread will exit

v2.7.0.1

**Comment by zctea** [comment]
The same problem as you.

**Comment by NyaReddington** [comment]
打开设置文件CapsLock+settings.ini，在全局设置“[Global]”下加一行“allowClipboard=1”，允许独立剪贴板功能就可以了

**Comment by zyoung1024** [comment]
> 打开设置文件CapsLock+settings.ini，在全局设置“[Global]”下加一行“allowClipboard=1”，允许独立剪贴板功能就可以了
allowClipboard=1 是默认值的

**Comment by wo52616111** [comment]
麻烦有一样问题的同学留意一下有没使用别的剪贴板管理类软件？有可能是冲突了

**Comment by Quackgrass** [comment]
> 麻烦有一样问题的同学留意一下有没使用别的剪贴板管理类软件？有可能是冲突了

v2.7.0.1 我也出现过这个提示，但不是每次都有。有用 Ditto 管理剪贴板。
昨天更新到 v3.1.0 后，暂时还未出现。

**Comment by changdy** [comment]
> 麻烦有一样问题的同学留意一下有没使用别的剪贴板管理类软件？有可能是冲突了

您好, 我也是类似问题 ,使用了ditto .尤其是再复制excel中的数据时 ,会出现卡死情况. 我暂时不需要qbar 和capslock+的粘贴板有什么办法解决吗 .多谢

**Comment by wo52616111** [comment]
`caps+f12` 可以关闭剪贴板功能。excel 的复制卡死，跟这个 issue 描述的问题是两个问题，excel 卡死的问题，可能是 excel 的问题，反正其他剪贴板管理工具，在 excel 复制大块数据的时候也会有一样的问题。issue 描述的问题，应该就是跟其他剪贴板管理工具冲突了。

**Comment by wo52616111** [comment]
麻烦遇过这个问题的同学帮忙试试最新版本还会不会出现呗？

**Comment by JianFei-Cheng** [comment]
现在还是会出现这个情况

**Comment by Chivier** [comment]
Utools/Ditto 和这个会有冲突，目前解决方案就是先留存报错记录，之后把对应的那一小块功能删掉……

**Comment by Guiquan-27** [comment]
也是同样的问题。估计是剪切板有冲突

**Comment by ShiYunyi728** [comment]
治标不治本的方法,关闭剪贴板功能,或者使用火绒等弹窗拦截掉这个弹窗.反正这个报错只是弹窗,实际功能是没事的.
