### ISSUE TITLE
如果想添加capslock+ctrl+*应该怎么做？

### ISSUE THREAD

**Issue by wocala** [wo52616111/capslock-plus#3]
相比alt，我更习惯用capslock+ctrl，这个也是可以直接修改吗？
谢谢~

**Comment by wo52616111** [comment]
可以，直接在`capslock+.ahk`修改就行，把所有表示按键的`!`换成`^`就行

**Comment by wangxt0211** [comment]
怎么把caps_a设置成回车键啊，谢谢

**Comment by wo52616111** [comment]
`Capslock+Space`就是回车了
