### ISSUE TITLE
下载了源码，ahk打开会报错，是不是ahk版本的问题？

### ISSUE THREAD

**Issue by derline** [wo52616111/capslock-plus#31]
是不是ahk版本太新的原因？

**Comment by wo52616111** [comment]
能给下具体的报错吗？

**Comment by dj199209** [comment]
![image](https://user-images.githubusercontent.com/34909617/92354070-3344ac80-f114-11ea-8745-0151156e9824.png)

**Comment by wo52616111** [comment]
你好，这啥也没说就一张图的话我也不知道啥意思，如果也是怀疑 ahk 版本问题的话，请按说明页上写的 1.1+，但是不要用 2.x 版本的 ahk

**Comment by derline** [comment]
> 能给下具体的报错吗？

嗯，我用的是2.0的ahk，后来了解原因了。
