### ISSUE TITLE
【问题反馈】Win102004 Caps+F6 不能使窗口置顶

### ISSUE THREAD

**Issue by Fred-Qhin** [wo52616111/capslock-plus#35]
Windows 10 2004 Version

使用 CapsLock + F6 的时候不能使窗口置顶，我使用其他窗口置顶软件都管用。WindowsOnTop，DesktopPins等等

希望解决一下，就是想卸载那些软件😄

**Comment by wo52616111** [comment]
试了下发现可以用额，能说下你用的 Capslock+ 的版本吗？然后是有用过别的键盘试下吗？有可能是键位冲突，如果没有条件用别的键盘试，可以试试把功能设置到别的热键组合上试试看，具体设置看看 CapsLock+settingsDemo.txt

**Comment by Fred-Qhin** [comment]
我也不知道为啥🤣，我台式机电脑在 settings.ini 里面加了 “caps_f6=keyFunc_winPin“ 才能用，我的笔记本电脑就不用。
谢谢了🌹
