### ISSUE TITLE
没办法将 / 转为 \

### ISSUE THREAD

**Issue by VillainTss** [wo52616111/capslock-plus#38]
caps_slash=keyFunc_Backslash
我试了好多次,应该是这么写,但是没有反应,官网和设置Demo中都没有说明

**Comment by wo52616111** [comment]
`keyFunc_Backslashv` 是哪里找到的？好像没有这个动作？

**Comment by wo52616111** [comment]
`keyFunc_Backslashv` 是哪里找到的？好像没有这个动作？

**Comment by VillainTss** [comment]
那 caps+ /  转为 \ 应该怎么弄,我找不到这个写法

**Comment by wo52616111** [comment]
试试 `keyFunc_send("\")`

**Comment by wo52616111** [comment]
试试 `keyFunc_send("\")`

**Comment by VillainTss** [comment]
nice
