### ISSUE TITLE
希望加入当前光标所在行上方插入一行

### ISSUE THREAD

**Issue by mayl8822** [wo52616111/capslock-plus#39]

**Comment by mayl8822** [comment]
![GIF 2020-06-20 4-53-12](https://user-images.githubusercontent.com/3281620/85178832-171e3580-b2b2-11ea-8990-63ea3df88e3e.gif)

**Comment by wo52616111** [comment]
这个自己加个 keyFunc 就好
```
sendInput, {up}
sendInput, {end}
sendInput, {enter}
```
（没跑过，盲敲的）

具体可以看看 readme 的说明
