### ISSUE TITLE
请问怎么编译成exe，我编译后不能用

### ISSUE THREAD

**Issue by zszq** [wo52616111/capslock-plus#42]
使用鼠标右键compile script对CapsLock+.ahk文件进行编译成exe后打开不报错，也不能用，所有的组合键都没反应。还有一个就时是，自带的ctrl+v时，总是只v键起作用打开了输入法的v，要输入法打开的v再次粘贴才能粘贴。

**Comment by wo52616111** [comment]
autohotkey 提供有编译脚本，用那个编译吧。如果你的安装路径是默认的，那它位于：`C:\Program Files\AutoHotkey\Compiler\Ahk2Exe.exe`

**Comment by wo52616111** [comment]
刚没留意到后半个问题，就关了 issue，能再详细说下那个粘贴问题吗？我不太理解

**Comment by zszq** [comment]
1.就是打开了你这个软件之后，经常会发生，自带的ctrl+v这个组合键进行粘贴的的时候，ctrl没有起作用，只有v键起作用了。
2.还有就是我用那个编译了exe可以成功，但是打开后没有任何反应。快捷键都没有用。
3.翻译那个可以改进下吗？我给你发邮件了
3.这个中括号大括号还有尖括号这个，2.+的我编写小程序的很好用，可惜改了。https://camo.githubusercontent.com/0104ad1a8cb18eaa125c5cf394b29e05029eeeb1/68747470733a2f2f692e696d6775722e636f6d2f344546536d45512e706e67我发现这个按键布局还不错，写代码很方便，就是没有窗口透明，窗口透明调试起来真是方便啊。

**Comment by zszq** [comment]
我对你的按键布局进行了些更改，但是编译成exe的时候就不行，我想请教下你编译成exe的时候进行什么处理了吗

**Comment by wo52616111** [comment]
1. 没有遇到过这个情况，测试不了，请问你用微软的输入法也会这样吗？就是粘贴不了
2. 编译的话，我这边也没有什么特别操作，选择 ahk，选择 exe 保存路径，选择 .ico，然后 base file 选默认，最后一行压缩，我有勾选，但是记得是无所谓的
3. 我看看
4. 这些功能你都可以通过设置找回来，甚至你可以直接用 2.x 的布局，具体看看 `CapsLock+SettingsDemo.txt`

**Comment by zszq** [comment]
ctrl+v这问题，我是用的搜狗输入法，后面测试下微软的看看有没有这种问题。
编译成后exe后没反应的问题找到了，被安全软件拦截了。。。。。。
有个问题想请教，就是我想用这个版本 https://github.com/PatrickShieh/CapsLockPlus，因为我也编程，这个用起来很舒服。但是我对autohotkey不熟悉，想问下这个版本怎么处理capslock短按切换大小写的问题，他这个版本不能切换。



              遇到困难时不要抱怨，既然改变不了过去，那么就努力改变未来！


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wo52616111"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月5日(星期天) 中午1:48
收件人:&nbsp;"wo52616111/capslock-plus"<capslock-plus@noreply.github.com&gt;;
抄送:&nbsp;"一切都会好起来的"<867309686@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wo52616111/capslock-plus] 请问怎么编译成exe，我编译后不能用 (#42)





  
没有遇到过这个情况，测试不了，请问你用微软的输入法也会这样吗？就是粘贴不了
 
编译的话，我这边也没有什么特别操作，选择 ahk，选择 exe 保存路径，选择 .ico，然后 base file 选默认，最后一行压缩，我有勾选，但是记得是无所谓的
 
我看看
 
这些功能你都可以通过设置找回来，甚至你可以直接用 2.x 的布局，具体看看 CapsLock+SettingsDemo.txt

**Comment by zszq** [comment]
编译成后exe后没反应的问题找到了，被安全软件拦截了。。。。。。
ctrl+v这问题，我是用的搜狗输入法，后面测试下微软的看看有没有这种问题。
