### ISSUE TITLE
CapsLock+settingsDemo.ini文档有小错误

### ISSUE THREAD

**Issue by zhongjimeiying** [wo52616111/capslock-plus#43]
> 459-460行，注释错误
> 原内容（应当为移动至页首）
; 选中至页首
caps_lalt_p=keyFunc_moveToPageBeginning

> 473-474行，注释错误
> 原内容（应当为选中至页首）
;移动至页首
caps_lalt_u=keyFunc_selectToPageBeginning

**Comment by wo52616111** [comment]
谢谢提醒，会改过来的
