### ISSUE TITLE
建议增加窗口布局管理

### ISSUE THREAD

**Issue by zhongjimeiying** [wo52616111/capslock-plus#47]
## 示例

1. +DownArrow  当前窗口占据下半屏幕
2. +LAlt LeftArrow  当前窗口占据左下角屏幕
3. +LeftArrow  当前窗口占据左半屏幕
4. +LAlt UpArrow  当前窗口占据左上角屏幕
5. +UpArrow  当前窗口占据上半屏幕
6. +LAlt RightArrow  当前窗口占据右上角屏幕
7. + RightArrow  当前窗口占据右半屏幕
8. +LAlt DownArrow  当前窗口占据右下角屏幕

**Comment by wo52616111** [comment]
这个 window + 方向键 就可以做到了呀？除了上/下半屏，其他都可以，可以试试？

**Comment by zhongjimeiying** [comment]
嗯，好，谢谢
