### ISSUE TITLE
感觉没必要用ijkl来选中,而是esdf+shift

### ISSUE THREAD

**Issue by BrontByte** [wo52616111/capslock-plus#48]
感谢大佬的软件十分好用.但是感觉选择文本这项操作用单独一套键位浪费了很多键位,学习成本很高还有点反习惯,如果改成esdf+shift来选中会方便很多,因为习惯的选中就是↑↓←→ + shift
我稍微改了改，似乎用起来还不错
[CapsLock+.ahk.txt](https://github.com/wo52616111/capslock-plus/files/4970142/CapsLock%2B.ahk.txt)
[CapsLock+settings.ini.txt](https://github.com/wo52616111/capslock-plus/files/4970188/CapsLock%2Bsettings.ini.txt)

**Comment by wo52616111** [comment]
这个感觉见仁见智，对于重度文字编辑的人，可能还是把选择单独出来好些，如果不习惯也可以像你这样——自己修改，挺好的
