### ISSUE TITLE
如何实现按某键位，光标所在行位于屏幕中央

### ISSUE THREAD

**Issue by dj199209** [wo52616111/capslock-plus#49]
如何实现按某键位，光标所在行位于屏幕中央？

**Comment by iamqiz** [comment]
你这个功能有点难,但是如果你能实现的话,加入到capslock里很简单,
比如用caps+m实现这个功能,那么你把这个功能用函数keyFunc_mid()实现之后 放在<源码根目录>\userAHK\main.ahk"里,让程序自动加载,,
然后在setting.ini的[Keys]字段下 写下caps_m=keyFunc_mid() 即可;
注意,你实现的函数名字必须以keyFunc_开头

**Comment by wo52616111** [comment]
@iamqiz 说得对，Capslock+ 主要是靠各种快捷键实现的功能（这样才能做到在各个软件都通用），不像编辑器软件对本身有完全的的控制权，这个功能应该是无法做到的，除非有快捷键可以居中。如果你只要求在某款软件使用这个功能，比如在软件 X，居中快捷键是`ctrl+shif+c`，那你可以写个函数，发送这个快捷键，虽然差不多，最终都是按快捷键，不过可能 `caps+xx` 会稍微顺手一点。
