### ISSUE TITLE
保存当前按键配置

### ISSUE THREAD

**Issue by gt-sun** [wo52616111/capslock-plus#5]
开机之后绑定了一堆窗口快捷键，每次重启都要再绑定一遍，非常麻烦，可以实现一个保存当前配置的功能，然后开机加载，就不需要每次都重新绑定一遍了，谢谢

**Comment by wo52616111** [comment]
不需要重新绑定的啊，现在就确实会保存配置的，窗口信息会存在`CapsLock+winsInfosRecorder.ini`里面，你看看是不是两次启动的不是同一个 exe，或者其他什么问题？

**Comment by gt-sun** [comment]
明白了，nice！
