### ISSUE TITLE
在这个可以在win10下使用么?

### ISSUE THREAD

**Issue by michelyao** [wo52616111/capslock-plus#50]
在win10下直接使用CapsLock+.ahk启动，启动后设置的键时灵时不灵。有没有谁遇到过这个问题呀。

**Comment by michelyao** [comment]
> 在win10下直接使用CapsLock+.ahk启动，启动后设置的键时灵时不灵。有没有谁遇到过这个问题呀。

;------------ Encoding: UTF-16 ------------
;请对照 CapsLock+settingsDemo.ini 来配置相关设置
[Global]

loadScript=scriptDemo.js

[QSearch]

[QRun]

[QWeb]

[TabHotString]

[QStyle]

[TTranslate]

[Keys]
caps_f7=keyFunc_example2

**Comment by wo52616111** [comment]
Capslock+ 支持 win10 的，你说的这个情况没有其他人反馈过，也没有信息，先暂时关闭了，如果有更多信息提供的话欢迎重新打开。
