### ISSUE TITLE
删除不想用的keys

### ISSUE THREAD

**Issue by jaggerjiang** [wo52616111/capslock-plus#51]
比如` caps+w` 。是在capslock+setting.ini 修改嘛

**Comment by iamqiz** [comment]
对,在setting.ini的[Keys]字段下添加如下代码
caps_w=keyFunc_doNothing
就可以使它无效了,
利用的就是keyFunc_doNothing这个函数啥也不干的特性

**Comment by jaggerjiang** [comment]
thanks
