### ISSUE TITLE
win10检测到木马

### ISSUE THREAD

**Issue by Drrany** [wo52616111/capslock-plus#54]
![image](https://user-images.githubusercontent.com/58012590/90575265-9fa34e80-e1ed-11ea-9fd8-8daaf1886ab1.png)

**Comment by bakaEC** [comment]
同，允许在设备上后依然报毒无法打开

**Comment by wo52616111** [comment]
- 保证是从官网下载的版本
- 添加到杀软白名单
- 如果还不行的话，可以试试下载 github 这里的源码运行，效果是一样的
