### ISSUE TITLE
Linux 下Capslock+的实现方法

### ISSUE THREAD

**Issue by Chivier** [wo52616111/capslock-plus#58]
Linux 下 AHK 是不太方便的（开WINE去跑AHK实在有点蠢）
可以使用 xmodmap 去实现键盘映射，下面是一个简单的例子：
```bash
 clear lock
 clear mod1
 clear mod3
 clear mod4
 clear mod5
 add mod1 = Alt_L Alt_R
 add mod3 = Hyper_L Hyper_R
 add mod4 = Super_L Super_R
 add mod5 = ISO_Level3_Shift
 
 keycode 66 = Mode_switch Caps_Lock NoSymbol NoSymbol
 keycode 39 = s S Left Left
 keycode 40 = d D Down Down
 keycode 41 = f F Right Right
 keycode 26 = e E Up Up
 
 keycode 31 = i I Prior Prior
 keycode 44 = j J Home Home
 keycode 45 = k K Next Next
 keycode 46 = l L End End 
```

`keycode id key_a key_b key_c key_d`

的含义是 id 的键位的映射为：

- 直接按下 key_a
- shift + id 等价于 key_b
- capslock + id 等价于 key_c

**Comment by Chivier** [comment]
但是 Qbar 等功能就无法实现了……
（简单随口一提，Linux用户表示非常想要一个Linux版本的capslock+）

**Comment by Smith-Wang** [comment]
用AutoKey可以实现更多的按键,但是Firefox等部分软件的兼容性不好...

**Comment by 517477981** [comment]
> 用AutoKey可以实现更多的按键,但是Firefox等部分软件的兼容性不好...

试了一下用autokey感觉太慢了可能是我使用不对

**Comment by NoviceButLove** [comment]
如果想配置为Vim(类似), 只需要修改一下即可，感谢[Chivier](https://github.com/Chivier)

将
> ```shell
>  clear lock
>  clear mod1
>  clear mod3
>  clear mod4
>  clear mod5
>  add mod1 = Alt_L Alt_R
>  add mod3 = Hyper_L Hyper_R
>  add mod4 = Super_L Super_R
>  add mod5 = ISO_Level3_Shift
>  
>  keycode 66 = Mode_switch Caps_Lock NoSymbol NoSymbol
>  keycode 39 = s S Left Left
>  keycode 40 = d D Down Down
>  keycode 41 = f F Right Right
>  keycode 26 = e E Up Up
>  
>  keycode 31 = i I Prior Prior
>  keycode 44 = j J Home Home
>  keycode 45 = k K Next Next
>  keycode 46 = l L End End 
> ```


修改为

> 上面保留  
> ~~keycode 39 = s S Left Left~~
> ~~keycode 40 = d D Down Down~~
> ~~keycode 41 = f F Right Right~~
> ~~keycode 26 = e E Up Up~~
> keycode 43 = h H Left Left
> keycode 44 = j J Down Down
> keycode 45 = k K Up Up
> keycode 46 = l L Right Right

---

此外还可以配置$ 和 ^
```bash
keycode 13 = 4 dollar End End 
keycode 15 = 6 asciicircum Home Home
```

**Comment by another-le** [comment]
完全的capslock+功能，可以参考一下：
```
clear lock
clear mod3

! 设置 CapsLock 为 Mode_switch
keycode 66 = Mode_switch
add mod3 = Mode_switch

! 方向键配置
keycode 39 = s S Left Left
keycode 40 = d D Down Down
keycode 41 = f F Right Right
keycode 26 = e E Up Up

! Delete 功能
keycode 27 = r R Delete NoSymbol
keycode 47 = semicolon colon End NoSymbol      ! CapsLock + ; = End
keycode 33 = p P Home NoSymbol                 ! CapsLock + p = Home
keycode 25 = w W BackSpace NoSymbol            ! CapsLock + w = BackSpace
```
但删除整行等功能没有实现

**Comment by another-le** [comment]
> 完全的capslock+功能，可以参考一下：
> 
> ```
> clear lock
> clear mod3
> 
> ! 设置 CapsLock 为 Mode_switch
> keycode 66 = Mode_switch
> add mod3 = Mode_switch
> 
> ! 方向键配置
> keycode 39 = s S Left Left
> keycode 40 = d D Down Down
> keycode 41 = f F Right Right
> keycode 26 = e E Up Up
> 
> ! Delete 功能
> keycode 27 = r R Delete NoSymbol
> keycode 47 = semicolon colon End NoSymbol      ! CapsLock + ; = End
> keycode 33 = p P Home NoSymbol                 ! CapsLock + p = Home
> keycode 25 = w W BackSpace NoSymbol            ! CapsLock + w = BackSpace
> ```
> 
> 但删除整行等功能没有实现
添加一个换行功能：
```
keycode 36 = Return NoSymbol Return NoSymbol    ! CapsLock + Enter = 换行
```
