### ISSUE TITLE
如何直接disable掉caps

### ISSUE THREAD

**Issue by zhengbli** [wo52616111/capslock-plus#6]
常常误操作打开了大写锁定，所以想索性把大写锁定给关了。尝试了设置
SetCapsLockState, AlwaysOff
貌似没有用

**Comment by wo52616111** [comment]
建议可以把`Capslock+.ahk`第`83`行：
```autohotkey
if CapsLock2
{
    SetCapsLockState, % GetKeyState("CapsLock","T") ? "Off" : "On"
}
```

改成：

```autohotkey
if CapsLock2
{
    sendinput, {esc}
}
```

那样短按 `Capslock` 就是 `esc`，我自己用也这么改了

**Comment by zhengbli** [comment]
非常感谢!

**Comment by wo52616111** [comment]
顺便说下，如果你按上面那样把`Capslock`改成了`esc`，按`Shift+Capslock`是可以切换大小写的

**Comment by Stupidman1998** [comment]
最新版我尝试了一下改.ahk文件，没生效。我改了settings.ini文件的
`[Keys]
;短按 Caps Lock -> 发送 Esc
press_caps=keyFunc_esc

;短按 Caps Lock -> 切换大小写
;press_caps=keyFunc_toggleCapsLock`
将切换大小写注释掉，放开发送Esc的注释，就能屏蔽大小写了。

**Comment by ChrisGray0626** [comment]
> 最新版我尝试了一下改.ahk文件，没生效。我改了settings.ini文件的
> 
> ```
> [Keys]
> ;短按 Caps Lock -> 发送 Esc
> press_caps=keyFunc_esc
> 
> ;短按 Caps Lock -> 切换大小写
> ;press_caps=keyFunc_toggleCapsLock
> ```
> 
> 将切换大小写注释掉，放开发送Esc的注释，就能屏蔽大小写了。

翻了一下我好像并没有找到相关配置，是不是更新了啊

**Comment by songtengfei95** [comment]
> 顺便说下，如果你按上面那样把`Capslock`改成了`esc`，按`Shift+Capslock`是可以切换大小写的

我现在把短按Caps改成Backspace，但是长按没有反应，怎么实现长按Caps也是Backspace呢？谢谢
