### ISSUE TITLE
这个可以装到linux 系统中吗？比如manjaro

### ISSUE THREAD

**Issue by bladelei** [wo52616111/capslock-plus#61]
如题

**Comment by Chivier** [comment]
Linux Wine 下面去开 AutoHotKey 是可以的。WineHQ里面维护了一个AHK，不过可能版本不够新，会有一点兼容性问题。
参考如下
[WineHQ AHK](https://appdb.winehq.org/objectManager.php?sClass=application&iId=5173)
[AHK Forum - My experience porting AHK scripts to Linux](https://www.autohotkey.com/boards/viewtopic.php?t=65552)

**Comment by Chivier** [comment]
不过个人推荐另一种方法，使用 xmodmap 去实现你需要的映射。
参考 #58

**Comment by wo52616111** [comment]
不可以的，ahk 只能在 windows 平台跑。@Chivier 谢谢回复
