### ISSUE TITLE
旧版有道api挂了?

### ISSUE THREAD

**Issue by DH-Illidan** [wo52616111/capslock-plus#64]
![image](https://user-images.githubusercontent.com/55729509/98235615-050d0d00-1f9d-11eb-8ef3-b3138a34f430.png)

**Comment by Chivier** [comment]
并没有，你是不是是选中了奇怪的字符之类的东西，选中你需要翻译的东西之后再使用Capslock+F3

**Comment by XueYuSky** [comment]
我也发现有道云API用不了了。好像要使用新的API平台接口

**Comment by XueYuSky** [comment]
但新的平台在Capslock+不能用

**Comment by DH-Illidan** [comment]
> 我也发现有道云API用不了了。好像要使用新的API平台接口
这个问题我看源码解决了, 在自己的配置中把apikey去掉就行了, 现在还可以用 2021年3月4日 13点51分

![image](https://user-images.githubusercontent.com/55729509/109917768-d4da3e80-7cf0-11eb-8358-6541f06b18cb.png)
