### ISSUE TITLE
建议增加其它按键映射方法

### ISSUE THREAD

**Issue by qiuzip** [wo52616111/capslock-plus#65]
想把Tab键映射为Backspace键，虽然Ahk本身是支持按键映射的，可以通过源码来修改，但还是希望Capslock+能自带映射方法。谢谢

**Comment by qiuzip** [comment]
press_tab=keyFunc_backspace

**Comment by Fred-Qhin** [comment]
`Cpaslock + w` 不就是退格键嘛，`Capslock + r` 就是 `Delete` 键

**Comment by wo52616111** [comment]
如果你是指修改组合键，可以参考：https://github.com/wo52616111/capslock-plus/issues/94

如果是指修改单个键盘上的按键，这已经超出 Capslock+ 的工作范围了，这事不应该由 Capslock+ 来做，你就直接用 ahk 改吧
