### ISSUE TITLE
是否有集成这几个常用工具的功能

### ISSUE THREAD

**Issue by Majors** [wo52616111/capslock-plus#68]
TranslucentTB：一个状态栏透明的功能
7+ Taskbar Tweaker：主要是用于缩小侧边状态栏的宽度到最小，并且隐藏“开始”和“显示桌面”按钮功能

现在目前集中学习和了解使用Caps Lock+的功能了，目前配置了很多实用的快速操作功能，感谢博主制作这个更容易入门和使用的工具。
上面两个工具目前也很多在乎简介效率美化的人在用，希望集成这方面功能，谢谢。

虽然那两个软件还是很棒，但是还是希望少运行两个进程在后台，感谢：）

**Comment by FredChin** [comment]
这个我觉得不太可能，这是美化系统的工具，跟这个输入效率没一点关系。

这两个东西我也用过，现在觉得也不怎么好用，不如原生的方便
