### ISSUE TITLE
想在qbar中调用有道翻译的面板

### ISSUE THREAD

**Issue by neibor** [wo52616111/capslock-plus#7]
平常使用的时候会遇到无法选中的单词 , capslocks又不能像有道客户端那样有图片取词的功能, 只能手敲, 直接调用有那个翻译面板比开浏览器简单一点.

**Comment by wo52616111** [comment]
不选中的情况下 `Capslock+T`，然后输入要翻译的东西，`Enter`

**Comment by neibor** [comment]
@wo52616111 原来如此 , 谢谢了
