### ISSUE TITLE
请问可以支持移动鼠标吗?想扔掉鼠标

### ISSUE THREAD

**Issue by sisrfeng** [wo52616111/capslock-plus#70]
capslock那个项目可以按hjkl移动鼠标, 请问你这里是抛弃这个功能了吗？他那个鼠标移动太慢了，我看你代码里有鼠标加速的内容，但没找到怎么用。可以麻烦大佬介绍一下嘛？谢谢！

**Comment by wo52616111** [comment]
目前是没有移动鼠标的功能的，那个调节是临时调节鼠标速度。目前也没时间写，如果能写 AHK 的话欢迎开个 PR 做一下～

**Comment by FredChin** [comment]
> capslock那个项目可以按hjkl移动鼠标, 请问你这里是抛弃这个功能了吗？他那个鼠标移动太慢了，我看你代码里有鼠标加速的内容，但没找到怎么用。可以麻烦大佬介绍一下嘛？谢谢！

![ThinkPad 蓝牙键盘](https://user-images.githubusercontent.com/39523950/104308239-5096e680-550b-11eb-82b0-42e0235c2d67.jpg)

ThinkPad 蓝牙键盘可以尝试一下

**Comment by wuqiang-zzu** [comment]
需求+1，扔掉鼠标

**Comment by snomiao** [comment]
lz可以看看 http://capslockx.snomiao.com/

**Comment by wo52616111** [comment]
已添加鼠标相关功能，感谢 @vict0rShen 的 PR https://github.com/wo52616111/capslock-plus/pull/117
具体按键函数可以看看：https://github.com/wo52616111/capslock-plus/blob/master/language/Simplified_Chinese.ahk#L684-L703 或 `Capslock+SettingsDemo.ini`

**Comment by PhoenixCODE2322** [comment]
@wo52616111  you have keys in mind to use these functions ? i would like to but i cannot find any keys ... can we use numpad keys ? also the trigger would be if numlock is off then keys will act as mouse movement  and if numlock is on then this functionality will be disabled

**Comment by sisrfeng** [comment]
> > capslock那个项目可以按hjkl移动鼠标, 请问你这里是抛弃这个功能了吗？他那个鼠标移动太慢了，我看你代码里有鼠标加速的内容，但没找到怎么用。可以麻烦大佬介绍一下嘛？谢谢！
> 
> ![ThinkPad 蓝牙键盘](https://user-images.githubusercontent.com/39523950/104308239-5096e680-550b-11eb-82b0-42e0235c2d67.jpg)
> 
> ThinkPad 蓝牙键盘可以尝试一下

指点杆(小红点)吗?  蓝牙的要500多块吧

**Comment by wo52616111** [comment]
> @wo52616111 you have keys in mind to use these functions ? i would like to but i cannot find any keys ... can we use numpad keys ? also the trigger would be if numlock is off then keys will act as mouse movement and if numlock is on then this functionality will be disabled

there is no default hotkeys for these functions, just set whatever hotkeys that capslock+ supported you want in Capslock+Settings.ini. take a look at Capslock+SettingsDemo.ini for more info
