### ISSUE TITLE
您好，请问新版本没有在文字两侧加引号的功能了吗

### ISSUE THREAD

**Issue by JianFei-Cheng** [wo52616111/capslock-plus#76]
之前的2.x版本有 在所选文字两侧加上 引号、小括号、大括号的功能，但现在的3.x版本好像不起作用了，我看文档说明里好像也没有写删除啊，是我漏看了吗？

**Comment by wo52616111** [comment]
在 3.x 的布局里确实去掉了，如果你习惯 2.x 的布局的话，要在 3.x 中使用 2.x 的热键布局，可以在 `CapsLock+settings.ini` > `[Global]` 下添加：`default_hotkey_scheme=capslock_plus`；如果你只想修改某个热键，在`[Keys]`下添加 `caps_quote=keyFunc_doubleChar("(", ")")` 。（不是很确认，人没在电脑前现在，你试试？）更详细的说明可以看看 `CapsLock+settingsDemo.ini`

**Comment by JianFei-Cheng** [comment]
> 在 3.x 的布局里确实去掉了，如果你习惯 2.x 的布局的话，要在 3.x 中使用 2.x 的热键布局，可以在 `CapsLock+settings.ini` > `[Global]` 下添加：`default_hotkey_scheme=capslock_plus`；如果你只想修改某个热键，在`[Keys]`下添加 `caps_quote=keyFunc_doubleChar("(", ")")` 。（不是很确认，人没在电脑前现在，你试试？）更详细的说明可以看看 `CapsLock+settingsDem的o.ini`

谢谢您，我对比了一下2.x的settingsDem，修改了几个热键，现在可以了，非常感谢

**Comment by JianFei-Cheng** [comment]
不好意思，我刚看到，新版本其实是有的，只是作者把替换了，你可以自己调出来的，我现在手边没有电脑所以没法发你，你可以比较下老版本的文档和新版本的文档，在老版本文档里有一个添加引号的设置功能键，你可以复制到新版本的设置中，我当初就是这么弄的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月6日(周四) 晚上9:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wo52616111/capslock-plus] 您好，请问新版本没有在文字两侧加引号的功能了吗 (#76)




 
Closed #76.

**Comment by wo52616111** [comment]
examples:
```
# Capslock+Settings.ini

[Keys]

# "..."
caps_quote=keyFunc_doubleChar(""")

# (...)
caps_9=keyFunc_doubleChar((,))

# {...}
caps_leftSquareBracket=keyFunc_doubleChar({,})

# [...]
caps_rightSquareBracket=keyFunc_doubleChar([,])

```

**Comment by TooFlow** [comment]
> examples:
> 
> ```
> # Capslock+Settings.ini
> 
> [Keys]
> 
> # "..."
> caps_quote=keyFunc_doubleChar(""")
> 
> # (...)
> caps_9=keyFunc_doubleChar((,))
> 
> # {...}
> caps_leftSquareBracket=keyFunc_doubleChar({,})
> 
> # [...]
> caps_rightSquareBracket=keyFunc_doubleChar([,])
> ```

请问中文的 “ ” ，该如何添加？
