### ISSUE TITLE
有没有某种方法，可以把这功能内嵌到键盘中

### ISSUE THREAD

**Issue by william-chin** [wo52616111/capslock-plus#77]

**Comment by wo52616111** [comment]
没有的，如果你的目标只是移动光标，或者发送简单的组合键，那你可以关注一下客制化键盘，或者很多键盘品牌都有提供自定义按键的软件。但是窗口绑定之类的功能，肯定是操作系统层面才能做到的。

一个配置客制化键盘按键的工具：https://caniusevia.com/
