### ISSUE TITLE
可以有linux吗？

### ISSUE THREAD

**Issue by KINGANDll** [wo52616111/capslock-plus#79]
习惯了capslock+以后，去用linux简直是折磨，有没有linux的解决方案？

**Comment by KINGANDll** [comment]
尽管我可以通过xmodmap实现capslock形式的上下左右，移动到行前行后，前后删除，但是前后选中不知道怎么实现，如果能够告诉我，不胜感激。
当然了，最好还是希望能够有linux的版本。

**Comment by wo52616111** [comment]
目前没有，暂时也没有计划写的，如果是 macOS 倒是有的，在官网就能找到。
