### ISSUE TITLE
有道翻译的API已经升级了

### ISSUE THREAD

**Issue by HanweiWu** [wo52616111/capslock-plus#81]
有道翻译的API已经升级了, 想修改成自己申请的API, get参数对不上, 这方面可以升级吗😟

**Comment by wo52616111** [comment]
这也有个 issue 关于翻译 API 的，https://github.com/wo52616111/capslock-plus/issues/46
现在我看有道翻译的 API，没有看到有提供免费使用，https://ai.youdao.com/price-center.s#servicename=fanyi-text
