### ISSUE TITLE
报 typora下 跳动多行会有循环跳动的情况。

### ISSUE THREAD

**Issue by xiao-peng-yu** [wo52616111/capslock-plus#83]
在一个 代码块中往下 跳5 行 最后会跳到 上面。而不是 一直往下面跳。
![bug](https://user-images.githubusercontent.com/68453850/118211260-796dbf00-b49e-11eb-82a7-89aa6073208d.gif)

**Comment by Aurora-kite** [comment]
> 在一个 代码块中往下 跳5 行 最后会跳到 上面。而不是 一直往下面跳。 ![bug](https://user-images.githubusercontent.com/68453850/118211260-796dbf00-b49e-11eb-82a7-89aa6073208d.gif) [ ![bug](https://user-images.githubusercontent.com/68453850/118211260-796dbf00-b49e-11eb-82a7-89aa6073208d.gif) ](https://user-images.githubusercontent.com/68453850/118211260-796dbf00-b49e-11eb-82a7-89aa6073208d.gif) [ ](https://user-images.githubusercontent.com/68453850/118211260-796dbf00-b49e-11eb-82a7-89aa6073208d.gif)

你好，你的typora代码块主题很好看！可以分享一下吗，谢谢！

**Comment by Aurora-kite** [comment]
> 在一个 代码块中往下 跳5 行 最后会跳到 上面。而不是 一直往下面跳。 ![bug](https://user-images.githubusercontent.com/68453850/118211260-796dbf00-b49e-11eb-82a7-89aa6073208d.gif) [ ![bug](https://user-images.githubusercontent.com/68453850/118211260-796dbf00-b49e-11eb-82a7-89aa6073208d.gif) ](https://user-images.githubusercontent.com/68453850/118211260-796dbf00-b49e-11eb-82a7-89aa6073208d.gif) [ ](https://user-images.githubusercontent.com/68453850/118211260-796dbf00-b49e-11eb-82a7-89aa6073208d.gif)

另外，我发现capslk+tab无法在typora中使用🤔
