### ISSUE TITLE
长按某个功能快捷键会激活大写锁定

### ISSUE THREAD

**Issue by windicold** [wo52616111/capslock-plus#9]
软件很方便，谢谢。用的是win8笔记本，可不可以设置另外一个组合键来替换capsloc本身大小写切换的功能（比如Esc+Space），然后又不影响capslock+的功能

**Comment by windicold** [comment]
下载页面已经是2.7.0.1版本，但源码还是2.7.0.0，旧版本的文件夹路径跳转时出现错误，提示没有注册类。
[![001.png](https://s25.postimg.org/hbmoxetkf/001.png)](https://postimg.org/image/hoe33lbu3/)

**Comment by windicold** [comment]
哦，那个名字显示2.7.0.1是我自己命名的，这个提示是运行旧版源码ahk编译后的文件
也就是2.7.0.0.exe才出现的，2.7.0.1没有这个问题

**Comment by wo52616111** [comment]
短按`Capslock`不就是切换大小写吗？为什么还要用其他组合键来实现这个功能呢？

**Comment by windicold** [comment]
怎么说呢，是因为我这边用了这么久，总会出现用capslock组合键实现光标移动的时候，按久了总会出现大小写切换，很头疼。
我就想如果只是我这边的问题的话，就想出换掉原本的短按caps键，换成组合键绕过这个问题来解决

**Comment by windicold** [comment]
你提供的最新版是2.7.0.1的已编译的程序，但源码是2.7.0.0。
但我技术菜，不太懂，试着改了源码实现组合键切换大小写后，出现了问题。
问题就是   文件夹路径跳转时出现错误

**Comment by wo52616111** [comment]
目前的85行中，把
```autohotkey
if CapsLock2
{
    SetCapsLockState, % GetKeyState("CapsLock","T") ? "Off" : "On"
}
```

```autohotkey
修改为：
if CapsLock2
{
    Sendinput, {esc}
}
```

可以让短按`Capslock`发送`Esc`，而不是大小写切换，大小写切换功能实际可以用`Shift+XX`代替，确实要切换的话可以在做了以上修改之后按`Shift+Capslock`，或者再用 autohotkey 绑其他组合键来实现大小写切换。只要把`SetCapsLockState, % GetKeyState("CapsLock","T") ? "Off" : "On"`这句放到其他组合键下执行应该就可以了。

**Comment by windicold** [comment]
我选择了折中方案。
初衷是想解决意外激活大写锁定问题，
修改了这些地方
77行
```autohotkey
SetTimer, setCapsLock2, -300 ; 300ms 犹豫操作时间
```
修改为
```autohotkey
SetTimer, setCapsLock2, -800 ; 800ms 犹豫操作时间
```
85行
```autohotkey
if CapsLock2
{
    SetCapsLockState, % GetKeyState("CapsLock","T") ? "Off" : "On"
}
```
修改为
```autohotkey
if CapsLock2
{
    SetCapsLockState, % GetKeyState("CapsLock","T") ? "Off" : "Off"
}
```
实现了只有在按`Shift+Capslock`的时候切换大小写，否则一般为小写。
谢谢你的帮助， @wo52616111 。
