### ISSUE TITLE
How does Capslock+ assign itself to run with this "Ctrl + Alt + Caps Lock" ?

### ISSUE THREAD

**Issue by PhoenixCODE2322** [wo52616111/capslock-plus#93]
![image](https://user-images.githubusercontent.com/75798544/150380411-3449d8bf-39be-4653-b01d-adde430fccf5.png)

i want to know how does this work. i want to it with my some personal scripts too.

**Comment by PhoenixCODE2322** [comment]
i asked on AHK discord.

**Comment by wo52616111** [comment]
Just take a look at here, if you haven't found the answer yet
https://github.com/wo52616111/capslock-plus/blob/e6390f03122ab13b2dc942c11804d1e026d1b28c/lib/lib_settings.ahk#L318-L331

**Comment by PhoenixCODE2322** [comment]
Thak you i got the answer. forgot to close the issue. My bad.

Thanks for this wonderful script.
