### ISSUE TITLE
如何把caps_f设置为ctrl_f？

### ISSUE THREAD

**Issue by danny1879** [wo52616111/capslock-plus#94]
demo文件里似乎不支持ctrl组合键？我想用caps代替ctrl，谢谢大佬。

**Comment by wo52616111** [comment]
试试这样？

```ini
[Keys]
caps_f=keyFunc_send(^f)
```

**Comment by danny1879** [comment]
谢谢。还有请问哪里有符号对应的键名？比如我不知道caps+'应该用caps_quote，'对应quote这个单词的对应表哪里可以查到呢？

**Comment by danny1879** [comment]
还有请问数字是怎么指向？比如我想设置caps_lalt_k=1，但这样写没有生效

**Comment by wo52616111** [comment]
>     * 请问哪里有符号对应的键名？比如我不知道`caps+'`应该用`caps_quote`，'对应quote这个单词的对应表哪里可以查到呢？

`Capslock+SettingsDemo.ini` 里有说明，源码： https://github.com/wo52616111/capslock-plus/blob/e6390f03122ab13b2dc942c11804d1e026d1b28c/language/Simplified_Chinese.ahk#L423

>     * 请问数字是怎么指向？比如我想设置`caps_lalt_k=1`，但这样写没有生效。如果用`caps_lalt_k=keyFunc_send(1)`的写法，在win10的计算器里按一次会输入11（其它版本没测试）。我用ahk原生写法`!J::send {1}`也会输入11。

那。。这可能是 ahk 或者计算器的问题吧，或者你试试 sendInput

>     * `caps_lalt_j=keyFunc_send(1)`是正常的（除了win计算器），但`caps_lalt_m=keyFunc_send(0)`没有反应。

加上双引号看看？人现在不在 windows 上，盲回的，没测试

>     * `caps_lalt_backslash=keyFunc_send(+)`这样设置的话会变成删除前一个字符，应该怎样设置？

你应该按 ahk 的符号规则，这应该是 `keyFunc_send("+=")` 这样？就是 `shift` + `=`
（同上，盲回的，你试试）

>     * `ctrl+c`复制的内容，无法用`caps+v`粘贴，请问有办法解决吗？

`caps+v` 本来就是独立的另一套剪贴板，对应 `caps+c`，麻烦先看看说明

>     * 好像没有支持shift键？想要`caps+shift`的操作应该如何设置？

现在确实没有，有需求的话可以自己 clone 源码修改，也欢迎提交代码合并更新，让其他人也能收益

>     * 我想设置`caps+f5`为`ctrl+f5`，但caps_f5=keyFunc_send(^F5)不可以，应该怎样设置？

加上双引号看看？

**Comment by danny1879** [comment]
> > ```
> > * 请问哪里有符号对应的键名？比如我不知道`caps+'`应该用`caps_quote`，'对应quote这个单词的对应表哪里可以查到呢？
> > ```
> 
> `Capslock+SettingsDemo.ini` 里有说明，源码：
> 
> https://github.com/wo52616111/capslock-plus/blob/e6390f03122ab13b2dc942c11804d1e026d1b28c/language/Simplified_Chinese.ahk#L423
> 
> > ```
> > * 请问数字是怎么指向？比如我想设置`caps_lalt_k=1`，但这样写没有生效。如果用`caps_lalt_k=keyFunc_send(1)`的写法，在win10的计算器里按一次会输入11（其它版本没测试）。我用ahk原生写法`!J::send {1}`也会输入11。
> > ```
> 
> 那。。这可能是 ahk 或者计算器的问题吧，或者你试试 sendInput
> 
> > ```
> > * `caps_lalt_j=keyFunc_send(1)`是正常的（除了win计算器），但`caps_lalt_m=keyFunc_send(0)`没有反应。
> > ```
> 
> 加上双引号看看？人现在不在 windows 上，盲回的，没测试
> 
> > ```
> > * `caps_lalt_backslash=keyFunc_send(+)`这样设置的话会变成删除前一个字符，应该怎样设置？
> > ```
> 
> 你应该按 ahk 的符号规则，这应该是 `keyFunc_send("+=")` 这样？就是 `shift` + `=` （同上，盲回的，你试试）
> 
> > ```
> > * `ctrl+c`复制的内容，无法用`caps+v`粘贴，请问有办法解决吗？
> > ```
> 
> `caps+v` 本来就是独立的另一套剪贴板，对应 `caps+c`，麻烦先看看说明
> 
> > ```
> > * 好像没有支持shift键？想要`caps+shift`的操作应该如何设置？
> > ```
> 
> 现在确实没有，有需求的话可以自己 clone 源码修改，也欢迎提交代码合并更新，让其他人也能收益
> 
> > ```
> > * 我想设置`caps+f5`为`ctrl+f5`，但caps_f5=keyFunc_send(^F5)不可以，应该怎样设置？
> > ```
> 
> 加上双引号看看？

感谢！

**Comment by wo52616111** [comment]
补充例子

```ini
[Keys]
# 短按 Caps Lock：发送 Win + space
press_caps=keyFunc_send("#{space}")
```
