### ISSUE TITLE
大家分享的配置

### ISSUE THREAD

**Issue by wo52616111** [wo52616111/capslock-plus#98]
## 目的

这个 issue 是为了提供一个地方给大家分享自己的配置，以做到：
1. 给还不了解怎么设置的人一些参考
2. 分享自定义的功能，也就是放在 `userAHK/` 下的 `.ahk`代码，或 `loadScript/` 下的 `.js` 代码
3. 如果你经常在不同的电脑上使用，可以随时来到这里复制自己的配置（假设你不方便使用 U 盘或者网盘，也不熟悉/不想用 github 管理这个配置文件）
4. 等等

### 必须保证
1. 留下你在使用这个配置时的 Capslock+ 版本号，使用的是源码还是 Capslock+.exe
2. 保证设置是可用的

### 尽量做到
1. 写上说明，是干什么用的
2. 代码写上注释
3. 使用 markdown 提高你的代码可读性

## 例子

把 `CapsLock+Q` 替换成 Listary，并自动填入选中文字。

Capslock+ Version: `v3.2.0.0` ahk 源码

`/userAHK/main.ahk`
```ahk
; 激活 Listary，并将选中的文字填入输入框
;
; 亲测在 win11 下使用最新版 Listary 似乎体验不是很好，文字粘贴到 Listary 输入框时
; 不能瞬间完成，会一个个字符出现，以前不会这样的。在这种情况下其实不推荐 Capslock+
; 配合 Listary 这么用了，这里单纯作为示例。
keyfunc_listary(){
    ; 获取选中的文字
    selText:=getSelText()

    ; 发送 ctrl+alt+F 按键（同时 Listary 呼出快捷键设置成这个），呼出 Listary
    ; Listary 曾经的默认快捷键是 win+F，新版已经改了，这里请修改成你所设置的对应快捷键
    sendinput, ^!{f}

    ; 等待 Listary 输入框打开
    winwait, ahk_exe Listary.exe, , 0.5

    ; 如果有选中文字的话
    if(selText){
        ; 在选中的字前面加上"gg "，使用 google 搜索
        selText:="gg " . selText

        ; 输出刚才复制的文字，并按一下`home`键将光标移到开头，以方便加入其它关键词
        sendinput, %selText%{home}
    }
}
```

`CapsLock+settings.ini`
```ini
[Global]
loadScript=scriptDemo.js

[QSearch]

[QRun]

[QWeb]

[TabHotString]

[QStyle]

[TTranslate]

[Keys]
# 把 Capslock+Q 替换成 Listary
caps_q=keyfunc_listary()

```

**Comment by wo52616111** [comment]
> win10下测试无法调用Lisatry！

试了下确实是，这是因为 Listary 更新了，默认快捷键修改了，已修改上述例子。
另外，上面只是作为例子，刚刚测试了下，在 win11 下使用最新版 Listary 配合 Capslock+，体验不那么好了，文字到 Listary 输入框不是瞬时的。

**Comment by TooFlow** [comment]
> ```ahk
>     ; 发送 ctrl+alt+F 按键（同时 Listary 呼出快捷键设置成这个），呼出 Listary
>     ; Listary 曾经的默认快捷键是 win+F，新版已经改了，这里请修改成你所设置的对应快捷键
>     sendinput, ^!{f}
> ```

请教，Listary的快捷键是WIN+Y，“ sendinput, ^!{f}”该如何修改？🥺

**Comment by wo52616111** [comment]
> > ```ahk
> >     ; 发送 ctrl+alt+F 按键（同时 Listary 呼出快捷键设置成这个），呼出 Listary
> >     ; Listary 曾经的默认快捷键是 win+F，新版已经改了，这里请修改成你所设置的对应快捷键
> >     sendinput, ^!{f}
> > ```
> 
> 请教，Listary的快捷键是WIN+Y，“ sendinput, ^!{f}”该如何修改？🥺

`sendinput, #{f}`

**Comment by TooFlow** [comment]
> > > ```ahk
> > >     ; 发送 ctrl+alt+F 按键（同时 Listary 呼出快捷键设置成这个），呼出 Listary
> > >     ; Listary 曾经的默认快捷键是 win+F，新版已经改了，这里请修改成你所设置的对应快捷键
> > >     sendinput, ^!{f}
> > > ```
> > 
> > 
> > 请教，Listary的快捷键是WIN+Y，“ sendinput, ^!{f}”该如何修改？🥺
> 
> `sendinput, #{f}`

谢谢解惑！按上述设置Listary可以与Caps+配合使用。
但关于段给大家一点提示：
 ; 如果有选中文字的话
    if(selText){
        ; 在选中的字前面加上"gg "，使用 google 搜索
        selText:="gg " . selText

在运行Listay时，建议把输入法调成英文状态，如果是中文状态，“gg” 会变成中文……

另一个是，发现Caps+没有“撤销”功能，如果需要，可在  /userAHK/main.ahk 下附上： 

; Caps+z = Ctrl+z，增加撤销功能。
keyfunc_CtrlZ(){

    sendinput,^{z}

}

……\capslock-plus-master\CapsLock+settings.ini 下加上：
[Keys]
caps_z=keyfunc_CtrlZ()

**Comment by TooFlow** [comment]
参照上例，附上自用的Caps+F3，本地调用Goldendict查询单词例子：

> keyfunc_Goldendict(){
    ; 获取选中的文字
    selText:=getSelText()

    ; 发送 ctrl+alt+c 按键（同时 Goldendict 中“使用下列热键翻译剪贴板中的单词”设置成这个，也可自行修改）
    sendinput, ^!{c}

    ; 等待 Goldendict 输入框打开,“C:\Program Files\GoldenDict\GoldenDict.exe”为Goldendict安装路径，请修改。
    winwait, ahk_exe C:\Program Files\GoldenDict\GoldenDict.exe, , 0.5

    ; 如果有选中文字的话
    if(selText){
        
        ; 输出刚才复制的文字，并按一下`end`键将光标移到结尾，并按“Enter”查询
        sendinput, %selText%{end}
        
    }
    sendinput, {Enter}
}

**Comment by willhome360** [comment]
个人分享一套我的快捷键设计方案，基于2.7版的键位布局。
原则1：是我认为左手需要完全负责光标移动，所以把第三套剪贴板取消，窗口激活只需要压倒最底，激活最左|最右这3个，这样就可以空出键位把原来需要2个手合作的动作实现左手操作。
原则2：我认为右手的队列操作都是多余的，把键位空出来作选中操作。

`[Keys]
press_caps=keyFunc_esc

; alt + left
caps_lalt_q=keyFunc_send(!{Left})

; alt + right
caps_lalt_t=keyFunc_send(!{Right})

; 移动至页首
caps_lalt_e=keyFunc_moveToPageBeginning

; 移动至页尾
caps_lalt_d=keyFunc_moveToPageEnd

; 移动至行首
caps_lalt_s=keyFunc_home

; 移动至行尾
caps_lalt_f=keyFunc_end

; 左移10次
caps_lalt_a=keyFunc_moveLeft(10)

; 右移10次
caps_lalt_g=keyFunc_moveRight(10)

; 上移一页
caps_lalt_t=keyFunc_pageUp

; 下移一页
caps_lalt_v=keyFunc_pageDown



; 激活最左边窗口
caps_lalt_x=keyFunc_activateSideWin(fl)

; 激活最右边窗口
caps_lalt_c=keyFunc_activateSideWin(fr)



; caps + ; 选中右边单词
caps_semicolon=keyFunc_selectWordRight

; 选中左边3个单词
caps_lalt_h=keyFunc_selectWordLeft(3)

; 选中右边3个单词
caps_lalt_semicolon=keyFunc_selectWordRight(3)

; 选中光标到页首
caps_lalt_u=keyFunc_selectToPageBeginning

; 选中光标到页尾
caps_lalt_o=keyFunc_selectToPageEnd

; 给以后留着键位
caps_n=keyFunc_doNothing
caps_p=keyFunc_doNothing`
