### ISSUE TITLE
能否输入单个字符

### ISSUE THREAD

**Issue by yrqyrqyrq99** [wo52616111/capslock-plus#99]
作者您好，请问通过 Capslock+ 能否实现单个字符的输入？比如我想映射 `capslock + 1` 为输入字符 `!`，该如何设置呢？
Ps：我尝试了使用 `keyFunc_doubleChar` 函数，但是它只能输入成对字符，或者是将单个字符输入到光标右侧

**Comment by wo52616111** [comment]
看看这里：https://github.com/wo52616111/capslock-plus/issues/94

**Comment by yrqyrqyrq99** [comment]
谢谢作者，问题已解决，使用 `keyFunc_sendChar(!)` 即可输入单个字符 `!`
